name: Build SLCAN Firmware
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    -name: Checout repo
  uses: actions/checout@v4

  -name: Install toolchain
  run: |
    sudo apt update
    sudo apt install -y gss-arm-none-eabi make

    -name: Build firmware
    run: |
      make

    -name: Upload firmware
    uses: actions/upload-artifact@v4
    with:
      name: firmware
      path: |
        **/*.bin
        **/*.elf
